export const SAVE_TRANSPORT_ROUTE_RATE = "SAVE_TRANSPORT_ROUTE_RATE";
export const SAVE_TRANSPORT_ROUTE_RATE_REQUEST =
  "SAVE_TRANSPORT_ROUTE_RATE_REQUEST";
export const SAVE_TRANSPORT_ROUTE_RATE_FAIL = "SAVE_TRANSPORT_ROUTE_RATE__FAIL";
export const SAVE_ALL_TRANSPORT_ROUTE_RATES = "SAVE_ALL_TRANSPORT_ROUTE_RATES";
export const LOADING_ALL_TRANSPORT_ROUTE_RATES =
  "LOADING_ALL_TRANSPORT_ROUTE_RATES";
